# Site settings
title: Intro to C programming
email: james.w.howard@gmail.com
description: Site for intro to c programming class.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "jhoward.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  jhoward

# Build settings
markdown: redcarpet
permalink: pretty
